Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -5,9 +5,48 @@ on:
     branches: [ master ]
 
 jobs:
+  check_code: # Validates the code (see develop.yml)
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+      
+    - name: Set up JDK 1.8
+      uses: actions/setup-java@v1
+      with:
+        java-version: 1.8
+
+    - name: Cache local Maven repository
+      uses: actions/cache@v2
+      with:
+        path: ~/.m2/repository
+        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+        restore-keys: |
+          ${{ runner.os }}-maven-
+      
+    - name: Build with Maven
+      run: mvn -B clean package -Pproduction
+      
+    - name: Check for uncommited changes
+      run: |
+        if [[ "$(git status --porcelain)" != "" ]]; then
+          echo ----------------------------------------
+          echo git status
+          echo ----------------------------------------
+          git status
+          echo ----------------------------------------
+          echo git diff
+          echo ----------------------------------------
+          git diff
+          echo ----------------------------------------
+          echo Troubleshooting
+          echo ----------------------------------------
+          echo "::error::Unstaged changes detected. Locally try running: git clean -ffdx && mvn -B clean package -Pproduction"
+          exit 1
+        fi
+
   prepare_release:
     runs-on: ubuntu-latest
-
+    needs: [check_code]
     steps:
     - uses: actions/checkout@v2
       
@@ -157,10 +196,10 @@ jobs:
         asset_name: vaadin-maps-leaflet-flow-${{ steps.version.outputs.release }}.zip
         asset_content_type: application/zip
 
-  publish-pages: # Update online reference for dependencies and licenses
+  publish-pages:
     name: Publish dependencies and licenses to github pages
     runs-on: ubuntu-latest
-    
+    needs: [prepare_release]
     steps:
     - uses: actions/checkout@v2
       
